#!/bin/bash

if [[ $# -lt 2 ]]; then
	echo "Usage: ./geninput graphSize hopCount"
	exit
fi

size=$1
value=$(printf '%.0f' $size)
hop=$(printf '%.0f' $2)
mkdir -p graphdata
exec/genChainUniformStretch $value 0 > graphdata/genChainUniformStretch${size}.txt
exec/genChainExpStretch $value 0 > graphdata/genChainExpStretch${size}.txt
exec/gen2MeshUnweightedUniformStretch $value 0 > graphdata/gen2MeshUnweightedUniformStretch${size}.txt
exec/gen2MeshUnweightedExpStretch $value 0 > graphdata/gen2MeshUnweightedExpStretch${size}.txt
exec/gen2MeshUniformStretch $value 0 > graphdata/gen2MeshUniformStretch${size}.txt
exec/gen2MeshExpStretch $value 0 > graphdata/gen2MeshExpStretch${size}.txt
exec/gen3MeshUnweightedUniformStretch $value 0 > graphdata/gen3MeshUnweightedUniformStretch${size}.txt
exec/gen3MeshUnweightedExpStretch $value 0 > graphdata/gen3MeshUnweightedExpStretch${size}.txt
exec/gen3MeshWeightedUniformStretch $value 0 > graphdata/gen3MeshWeightedUniformStretch${size}.txt
exec/gen3MeshWeightedExpStretch $value 0 > graphdata/gen3MeshWeightedExpStretch${size}.txt
exec/genFixedLengthUniformStretch $value $hop 0 1 > graphdata/genFixedLengthUniformStretch${size}.txt
exec/genFixedLengthExpStretch $value $hop 0 1 > graphdata/genFixedLengthExpStretch${size}.txt
exec/genRandomUniformStretch $value $((2*$value)) > graphdata/genRandomUniformStretch${size}.txt
exec/genRandomExpStretch $value $((2*$value)) > graphdata/genRandomExpStretch${size}.txt

for file in genChainUniformStretch genChainExpStretch gen2MeshUnweightedUniformStretch gen2MeshUnweightedExpStretch gen2MeshUniformStretch gen2MeshExpStretch gen3MeshUnweightedUniformStretch gen3MeshUnweightedExpStretch gen3MeshWeightedUniformStretch gen3MeshWeightedExpStretch genFixedLengthUniformStretch genFixedLengthExpStretch genRandomUniformStretch genRandomExpStretch
do
	exec/graphsp2mm graphdata/${file}${size}.txt graphdata/${file}${size}.mtx
done
