#!/bin/bash
size=1e5
value=$(printf '%.0f' $size)
exec/genChainUniformStretch $value > data/genChainUniformStretch${size}.mtx
exec/genChainExpStretch $value > data/genChainExpStretch${size}.mtx
exec/gen2MeshUnweightedUniformStretch $value > data/gen2MeshUnweightedUniformStretch${size}.mtx
exec/gen2MeshUnweightedExpStretch $value > data/gen2MeshUnweightedExpStretch${size}.mtx
exec/gen2MeshWeightedUniformStretch $value > data/gen2MeshWeightedUniformStretch${size}.mtx
exec/gen2MeshWeightedExpStretch $value > data/gen2MeshWeightedExpStretch${size}.mtx
exec/gen3MeshUnweightedUniformStretch $value > data/gen3MeshUnweightedUniformStretch${size}.mtx
exec/gen3MeshUnweightedExpStretch $value > data/gen3MeshUnweightedExpStretch${size}.mtx
exec/gen3MeshWeightedUniformStretch $value > data/gen3MeshWeightedUniformStretch${size}.mtx
exec/gen3MeshWeightedExpStretch $value > data/gen3MeshWeightedExpStretch${size}.mtx
exec/genFixedLengthUnweightedUniformStretch $value 100 1 > data/genFixedLengthUnweightedUniformStretch${size}.mtx
exec/genFixedLengthUnweightedExpStretch $value 100 1 > data/genFixedLengthUnweightedExpStretch${size}.mtx
exec/genFixedLengthWeightedUniformStretch $value 100 1 > data/genFixedLengthWeightedUniformStretch${size}.mtx
exec/genFixedLengthWeightedExpStretch $value 100 1 > data/genFixedLengthWeightedExpStretch${size}.mtx
exec/genRandomWeightedUniformStretch $value $((2*$value)) 9 > data/genRandomWeightedUniformStretch${size}.mtx
exec/genRandomWeightedExpStretch $value $((2*$value)) 9 > data/genRandomWeightedExpStretch${size}.mtx
exec/genRandomUnweightedUniformStretch $value $((2*$value)) > data/genRandomUnweightedUniformStretch${size}.mtx
exec/genRandomUnweightedExpStretch $value $((2*$value)) > data/genRandomUnweightedExpStretch${size}.mtx
